%YAML:1.0

# this is an example mw_videoMotionTracking configuration file

# Mirror Worlds master server Address and Port
server:
    address: '127.0.0.1'
    port: 5555


cameras:
    - id: 1
      name: observation
      desc: Observation Room
      url: 'http://admin:admin@192.168.1.14/video.cgi?.mjpg'
      crop: [100, 100, 900, 700]

    - id: 2
      name: learningA
      desc: Learning Lab A
      url: 'http://admin:admin@192.168.1.15/video.cgi?.mjpg'
      crop: [70, 30, 900, 800]

    - id: 3
      name: learningB
      desc: Learning Lab B
      url: 'http://admin:admin@192.168.1.11/video.cgi?.mjpg'
      crop: [130, 260, 800, 550]

    - id: 4
      name: learningC
      desc: Learning Lab C
      url: 'http://admin:admin@192.168.1.10/video.cgi?.mjpg'
      crop: [130, 180, 800, 570]

    - id: 5
      name: learningD
      desc: Learning Lab D
      class: oncam
      url: 'http://admin:admin@192.168.1.12/video.cgi?.mjpg'
      crop: [130, 100, 800, 570]

    - id: 6
      name: hallwayA
      desc: Hallway A
      url: 'http://root:admin@192.168.1.16/video.mjpg'
      crop: [180, 90, 800, 800]

    - id: 7
      name: hallwayB
      desc: Hallway B
      url: 'http://root:admin@192.168.1.17/video.mjpg'
      crop: [180, 240, 750, 650]

    - id: 8
      name: hallwayC
      desc: Hallway C
      class: vivotek
      url: 'http://root:admin@192.168.1.18/video.mjpg'
      crop: [180, 250, 750, 650]

    - id: 9
      name: hallwayD
      desc: Hallway D
      url: 'http://root:admin@192.168.1.19/video.mjpg'
      crop: [180, 250, 750, 800]

    - id: 10
      name: hallwayE
      desc: Hallway E
      url: 'http://root:admin@192.168.1.20/video.mjpg'
      crop: [180, 250, 750, 726]

    - id: 11
      name: office11
      desc: My Room
      url: 'rtsp://192.168.1.4:554/live/ch1'
      crop: [0, 0, 0, 0]
