# This is a GNU make file that uses GNU make make extensions


INSTALL_DIR = $(PREFIX)/public/mw/css

INSTALLED := bootstrap.css bootstrap.css.map bootstrap.min.css bootstrap.min.css.map bootstrap-theme.css bootstrap-theme.css.map bootstrap-theme.min.css bootstrap-theme.min.css.map


include ../../../quickbuild.make
