# This is a GNU make file that uses GNU make make extensions

# to install opencv and then mw_videoMotionTracking
SUBDIRS := opencv mw_videoMotionTracking

#if opencv is already installed
#SUBDIRS := mw_videoMotionTracking


include ../quickbuild.make
