# This is a GNU make file that uses GNU make make extensions


# The file teapot.x3d.xxx is just a source file, that is used to generate
# many files. We did not give it a file suffix that would cause the build
# system to try to act on it based on a suffix build rule, hence it has a
# strange file suffix .xxx.

INSTALL_DIR = $(PREFIX)/public/mw/avatars

include ../../../quickbuild.make
