# This is a GNU make file that uses GNU make make extensions


INSTALL_DIR = $(PREFIX)/public/mw/fonts

INSTALLED := glyphicons-halflings-regular.eot glyphicons-halflings-regular.svg glyphicons-halflings-regular.ttf glyphicons-halflings-regular.woff glyphicons-halflings-regular.woff2


include ../../../quickbuild.make
